# Generated by Django 4.1.5 on 2023-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='acquisition_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
